name: Build

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ${{ matrix.runner }}

    permissions:
      packages: write
      contents: read

    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-musl
          - target: i686-unknown-linux-musl
          - target: aarch64-unknown-linux-musl
          - target: armv7-unknown-linux-musleabihf

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: "Dockerfile.${{ matrix.target }}"
          push: true
          tags: "ghcr.io/DorianNiemiecSVRJS/cross-${{ matrix.target }}"
          cache-from: type=gha
          cache-to: type=gha,mode=max
